spring:
  application:
    name: test14_security
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
    username: root
    password: javajava1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port: 8080